"""Add subtitle 2

Revision ID: 5dc25572f387
Revises: 3869e9f6ef49
Create Date: 2026-04-05 14:27:53.009106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc25572f387'
down_revision: Union[str, None] = '3869e9f6ef49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('subtitle_2', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_events_subtitle_2'), 'events', ['subtitle_2'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_subtitle_2'), table_name='events')
    op.drop_column('events', 'subtitle_2')
    # ### end Alembic commands ###
