/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as UsersAhmadIndexRouteImport } from './routes/users/ahmad/index'

const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersAhmadIndexRoute = UsersAhmadIndexRouteImport.update({
  id: '/users/ahmad/',
  path: '/users/ahmad/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/events/': typeof EventsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/users/ahmad/': typeof UsersAhmadIndexRoute
}
export interface FileRoutesByTo {
  '/events': typeof EventsIndexRoute
  '/users': typeof UsersIndexRoute
  '/users/ahmad': typeof UsersAhmadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/events/': typeof EventsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/users/ahmad/': typeof UsersAhmadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/events/' | '/users/' | '/users/ahmad/'
  fileRoutesByTo: FileRoutesByTo
  to: '/events' | '/users' | '/users/ahmad'
  id: '__root__' | '/events/' | '/users/' | '/users/ahmad/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  EventsIndexRoute: typeof EventsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  UsersAhmadIndexRoute: typeof UsersAhmadIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/ahmad/': {
      id: '/users/ahmad/'
      path: '/users/ahmad'
      fullPath: '/users/ahmad/'
      preLoaderRoute: typeof UsersAhmadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  EventsIndexRoute: EventsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  UsersAhmadIndexRoute: UsersAhmadIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
